# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import raft_pb2 as raft__pb2


class raftImplemetationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestVote = channel.unary_unary(
        '/raftImplemetation/RequestVote',
        request_serializer=raft__pb2.VoteReq.SerializeToString,
        response_deserializer=raft__pb2.Vote.FromString,
        )
    self.AppendEntries = channel.unary_unary(
        '/raftImplemetation/AppendEntries',
        request_serializer=raft__pb2.Empty.SerializeToString,
        response_deserializer=raft__pb2.Empty.FromString,
        )
    self.SendHeartBeat = channel.unary_unary(
        '/raftImplemetation/SendHeartBeat',
        request_serializer=raft__pb2.Heartbeat.SerializeToString,
        response_deserializer=raft__pb2.AckHB.FromString,
        )
    self.ReplicateFile = channel.unary_unary(
        '/raftImplemetation/ReplicateFile',
        request_serializer=raft__pb2.ReplicateFileInfo.SerializeToString,
        response_deserializer=raft__pb2.Empty.FromString,
        )
    self.DeleteFile = channel.unary_unary(
        '/raftImplemetation/DeleteFile',
        request_serializer=raft__pb2.ReplicateFileInfo.SerializeToString,
        response_deserializer=raft__pb2.Empty.FromString,
        )


class raftImplemetationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestVote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendEntries(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendHeartBeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicateFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_raftImplemetationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestVote': grpc.unary_unary_rpc_method_handler(
          servicer.RequestVote,
          request_deserializer=raft__pb2.VoteReq.FromString,
          response_serializer=raft__pb2.Vote.SerializeToString,
      ),
      'AppendEntries': grpc.unary_unary_rpc_method_handler(
          servicer.AppendEntries,
          request_deserializer=raft__pb2.Empty.FromString,
          response_serializer=raft__pb2.Empty.SerializeToString,
      ),
      'SendHeartBeat': grpc.unary_unary_rpc_method_handler(
          servicer.SendHeartBeat,
          request_deserializer=raft__pb2.Heartbeat.FromString,
          response_serializer=raft__pb2.AckHB.SerializeToString,
      ),
      'ReplicateFile': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicateFile,
          request_deserializer=raft__pb2.ReplicateFileInfo.FromString,
          response_serializer=raft__pb2.Empty.SerializeToString,
      ),
      'DeleteFile': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteFile,
          request_deserializer=raft__pb2.ReplicateFileInfo.FromString,
          response_serializer=raft__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'raftImplemetation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
